// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm2HDFOP5hnpegv_Lo4hwnztcD2-KBYRs',
    appId: '1:65046374503:web:b71695c05a8fdecf0b0cc2',
    messagingSenderId: '65046374503',
    projectId: 'tft-app-219e1',
    authDomain: 'tft-app-219e1.firebaseapp.com',
    storageBucket: 'tft-app-219e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmJBSJB3BOmilpaR7J2yQzIxrF24u-YP8',
    appId: '1:65046374503:android:48f21a93553a0a870b0cc2',
    messagingSenderId: '65046374503',
    projectId: 'tft-app-219e1',
    storageBucket: 'tft-app-219e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiWS-rdMpE-CuU3bA0CUoRoc0DtYtvYrE',
    appId: '1:65046374503:ios:97b387d272853dab0b0cc2',
    messagingSenderId: '65046374503',
    projectId: 'tft-app-219e1',
    storageBucket: 'tft-app-219e1.appspot.com',
    iosBundleId: 'com.example.tftApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiWS-rdMpE-CuU3bA0CUoRoc0DtYtvYrE',
    appId: '1:65046374503:ios:956e5fe7e0c642bb0b0cc2',
    messagingSenderId: '65046374503',
    projectId: 'tft-app-219e1',
    storageBucket: 'tft-app-219e1.appspot.com',
    iosBundleId: 'com.example.tftApp.RunnerTests',
  );
}
